### ISSUE TITLE
Upon restarting, Core is stuck on block 2778366

### ISSUE THREAD

**Issue by pioruns** [Nexusoft/NexusInterface#72] opened 2019-08-09 09:07 UTC
Freshly installed nexus_wallet-Linux-1.1.0.AppImage, fully synchronized. I closed the wallet and reopen again.
Core lost sync and now is stuck at block 2778366 for no apparent reason. I have 16 connections but blocks are not moving forward. Most recent block right now is 2778457, so I am 91 blocks behind and counting.

~/.Nexus/log/0.log attached.

[0.log](https://github.com/Nexusoft/NexusInterface/files/3485566/0.log)

**Comment by pioruns** [comment] 2019-08-09 11:53
Left it running for several hours, still stuck. This is freshly installed nexus on VM, bootstrapped from file, was synchronized just fine until I restarted it, now it' stuck.

New 0.log attached with additional entries.
[0.log](https://github.com/Nexusoft/NexusInterface/files/3486214/0.log)

**Comment by l8nit3tr0ubl3** [comment] 2019-08-09 12:12
I can confirm the same issue, windows and Linux,I have 3 copies running, 1 at 365 and 2 at 366

**Comment by Qrysto** [comment] 2019-08-09 16:03
@pioruns @l8nit3tr0ubl3 You're welcome to test out the latest code from Merging branch

**Comment by l8nit3tr0ubl3** [comment] 2019-08-09 17:06
error during build, i think its a transposed number issue:
`No matching version found for data-urls@^1.1.1` so does vm-browserify-1.1.1
And after checking the node registry, the newest version looks to be 1.0.1.
But a removal of package-lock.json and re-doing npm instal fixes this issue and allows to build.

Once built, the new 1.2.0 linux wallet

P.S.:
LOVE the new additions!
-Language chooser at startup
-Failing to start first run fxed!
-A new snap build
-Bootstrapping now, but looks like the "downloading message stcuk" is fixed too, will edit comment when verified :)

**Comment by l8nit3tr0ubl3** [comment] 2019-08-09 17:30
Loaded and synced (as far as it will) block 2,778,366 ambassador signatures invalid still.

**Comment by KenCorma** [comment] 2019-08-09 18:00
This is not a wallet issue but a blockchain issue due to some bad blocks being on the legacy chain but the tritium chain rejecting them. We are rolling out fixes for the network shortly.

**Comment by pioruns** [comment] 2019-08-09 19:23
Hard fork then? Legacy vs Tritium????

**Comment by l8nit3tr0ubl3** [comment] 2019-08-09 19:31
@pioruns that shouldn't be required for this, simply allowing the tritum wallet to "skip" a certain block range for sig checking should bypass the bad blocks, followed by a tritum update.

**Comment by pioruns** [comment] 2019-08-09 19:32
Instead of hardcoding skipping of rules for certain block, Tritium should be fixed to behave just like legacy wallet, to make full consensus. What if this happen again?

**Comment by l8nit3tr0ubl3** [comment] 2019-08-09 19:50
Tritum has security upgrades in it which is far better for the network, and legacy will be phased out. Allowing tritum to work as legacy would be a step backwards in security, I believe.

**Comment by pioruns** [comment] 2019-08-09 21:26
Then legacy should be immediately fixed, to keep the consensus.  Oh wait, legacy is way ahead with blocks so you cannot roll back the blockchain. Tritium will have to be patched up as you mentioned, forever accepting invalid blocks into it's chain. What a mess.

**Comment by l8nit3tr0ubl3** [comment] 2019-08-09 23:11
Running 1.2.0 built myself on windows 10 and network just restart again! :) Happily staking.

**Comment by KenCorma** [comment] 2019-08-10 00:49
This has been fixed with core 3.0.3 which is rolling out to all nodes and miners. However please talk here if there are any issues.

**Comment by l8nit3tr0ubl3** [comment] 2019-08-10 01:53
Still seems stuck, but now at 2,778,634. Log shows each new block found by legacy as orphan, but tritum chain not progressing beyond the number above. while legacy/pool chain currently 2,779,270

**Comment by KenCorma** [comment] 2019-08-10 04:01
I am being told it might take some time as seed nodes get updated for the blockchain to get to the right chain and height. I would say it could take a few more hours.  Just keep running the correct core and it will eventually sort its self out.

**Comment by pioruns** [comment] 2019-08-10 10:02
Does this new version of the core makes Legacy Wallet chain invalid?

**Comment by pioruns** [comment] 2019-08-10 14:49
**Tritium lost sync with Legacy Nexus network.
![2019-08-10 15_48_40-Debian Buster (Snapshot 2)  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/1646393/62823184-5a822080-bb86-11e9-91c5-cfbeedb7ceea.png)
![2019-08-10 15_48_24-nv01 VNC](https://user-images.githubusercontent.com/1646393/62823188-5ce47a80-bb86-11e9-85dc-898832a194a0.png)

**
Tritium wallet shows as fully synchonized and is on 2779557 block.
Legacy wallet shows as fully synchonized and is on 2779888 block.

**Comment by pioruns** [comment] 2019-08-10 15:49
About one hour later, status:
Tritium shows 2779639 fully synchronized
Legacy shows 2779935 fully synchronized

**Comment by l8nit3tr0ubl3** [comment] 2019-08-10 19:19
I believe it was said that 3.0.3 core is now a requirement. Which would make the legacy version now obsolete (or at least on it's own fork).
I see binance updating and nexplorer... haven't seen the GPU pool change yet though

**Comment by pioruns** [comment] 2019-08-10 22:08
That's a messy hardfork, that's for sure...

**Comment by KenCorma** [comment] 2019-08-12 23:46
This is not technically not a hard fork but we are making people and nodes/miners upgrade. 

I am going to close this as the network is rolling smoothly now.

**Closed by KenCorma** 2019-08-12 23:46 UTC
Labels: Backend, bug
