### ISSUE TITLE
1.1.0 wallet windows, wont bootstrap or abort bootstrap

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [Nexusoft/NexusInterface#61] opened 2019-07-21 13:31 UTC
First, very well done nexus dev team. That was an Incredibly fast rollout to fix the connection errors.

To reproduce:
Start new 1.1.0 wallet with a fresh PC (windows 10). Everything connects and wallet loads, however when choosing to bootstrap the counter hangs at 0%. Also when attempting to abort the bootstrapping the process hangs for 5+ minutes untill I eventually just restart the wallet. Standard syncing works just fine though.

Will update with log info when I'm done work, also will test the linux and osx versions

**Comment by Qrysto** [comment] 2019-07-22 04:03
Thank you for your bug report. This is probably not a bug on the bootstrap process itself but a bug on the core, happening on fresh start, the core would shut down after a while, making the bootstrap process malfunction. @l8nit3tr0ubl3 Could you confirm if it works well after closing and reopening the wallet (not a fresh start)?

**Comment by l8nit3tr0ubl3** [comment] 2019-07-22 04:08
You are 100% correct, I tried your workaround on a wallet that had normally synced 1M blocks or so, after shutting down and restarting all works fine. Both bootstrapping and aborting the bootstrapping.

One side note, when closing the wallet I received the "your wallet is not encrypted" message. However I had not received it up until then. Likely the shutdown sent a sigkill to whatever process has the bug, allowing the rest to try to start during the brief period before shutdown.

**Comment by Qrysto** [comment] 2019-07-24 04:50
Thank you @l8nit3tr0ubl3, I will have a look at the issue you mentioned in your update.

**Closed** 2019-08-12 22:07 UTC
Labels: bug
